services:
  db:
    image: postgres:latest
    container_name: cashtrack-db
    command: 'postgres -c max_connections=1000 -c shared_buffers=128MB -c synchronous_commit=off -c fsync=off -c full_page_writes=off'
    environment:
      POSTGRES_DB: # DATABASE NAME HERE #
      POSTGRES_USER: # DATABASE USERNAME HERE #
      POSTGRES_PASSWORD: # DATABASE PASSWORD HERE #
    ports:
      - 5438:5432
    volumes:
      - postgres-container-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "--username", "# DATABASE USERNAME HERE #", "--dbname", "# DATABASE NAME HERE #" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
  backend:
    image: cashtrack
    container_name: cashtrack_app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - POSTGRESQL_DATABASE_URL=jdbc:postgresql://db:5432/ #DATABASE NAME HERE#
      # SHOULD BE LIKE 
      # jdbc:postgresql://db:5432/cashtrack
      - POSTGRESQL_DATABASE_USERNAME= # DATABASE USERNAME HERE #
      - POSTGRESQL_DATABASE_PASSWORD= # DATABASE PASSWORD HERE #
      - JWT_KEY= # JWT SECRET KEY HERE #
volumes:
  postgres-container-data: